apiVersion: v1
kind: Pod
metadata:
  name: jenkins-build
  namespace: qa-ingrastructure
spec:
  containers:
  - name: docker
    image: docker:edge-git
    command: ["cat"]
    tty: true
    volumeMounts:
      - name: docker_socket
        mountPath: /var/run/docker.sock
  volumes:
  - name: docker_socket
    hostPath:
        path: /var/run/docker.sock
        type: Socket