apiVersion: v1
kind: Pod
metadata:
  name: jenkins-build
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: 
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /root
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
        name: regcred
        items:
          - key: .dockerconfigjson
            path: .docker/config.json